[tools]
go = "1.25.4"
groovy = "2.4.12"
java = "temurin-25.0.1+8.0.LTS"
kotlin = "2.2.21"
lua = "5.4.8"
maven = "3.6.3"
node = "24.11.1"
opam = "2.1.2"
python = "3.14.0"
ruby = "3.4.7"
rust = "1.91.1"
gradle = "6.8.1"
terraform = "1.3.9"
pulumi = "3.208.0"
kubectl = "1.34.2"
kompose = "1.22.0"
helm = "4.0.1"
kustomize = "5.8.0"
helm-docs = "1.14.2"
helm-ct = "3.12.0"
1password-cli = "2.24.0"
rclone = "1.69.1"
tflint = "0.60.0"
sbt = "1.11.7"
dotnet-core = "10.0.100"
uv = "0.9.21"
krew = "0.4.5"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "java", "node"]
