[tools]
go = "1.26.0"
groovy = "2.4.12"
java = "temurin-25.0.2+10.0.LTS"
kotlin = "2.3.10"
lua = "5.5.0"
maven = "3.6.3"
node = "24.13.1"
opam = "2.1.2"
python = "3.14.3"
ruby = "4.0.1"
rust = "1.93.0"
gradle = "6.8.1"
terraform = "1.14.5"
pulumi = "3.220.0"
kubectl = "1.35.1"
kompose = "1.22.0"
helm = "4.1.1"
kustomize = "5.8.1"
helm-docs = "1.14.2"
helm-ct = "3.12.0"
1password-cli = "2.24.0"
rclone = "1.69.1"
tflint = "0.61.0"
sbt = "1.12.2"
dotnet-core = "10.0.103"
uv = "0.10.2"
krew = "0.4.5"
"github:anomalyco/opencode" = "1.0.223"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "java", "node"]
